"""initial_schema

Revision ID: 083bc3634e98
Revises: 
Create Date: 2026-03-05 11:18:39.287006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '083bc3634e98'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.String(length=20), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('code', name=op.f('uq_departments_code')),
    sa.UniqueConstraint('name', name=op.f('uq_departments_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('student_id_number', sa.String(length=50), nullable=True),
    sa.Column('employee_id', sa.String(length=50), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('extra_time_factor', sa.Float(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_users_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('employee_id', name=op.f('uq_users_employee_id')),
    sa.UniqueConstraint('student_id_number', name=op.f('uq_users_student_id_number'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_groups_teacher_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_table('question_banks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_question_banks_teacher_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_banks'))
    )
    op.create_table('assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assessment_type', sa.String(length=30), nullable=False),
    sa.Column('format_type', sa.String(length=30), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('available_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('scoring_policy', sa.String(length=20), nullable=False),
    sa.Column('passing_score', sa.Float(), nullable=False),
    sa.Column('total_points', sa.Float(), nullable=False),
    sa.Column('score_release_policy', sa.String(length=30), nullable=False),
    sa.Column('shuffle_questions', sa.Boolean(), nullable=False),
    sa.Column('shuffle_options', sa.Boolean(), nullable=False),
    sa.Column('enforce_fullscreen', sa.Boolean(), nullable=False),
    sa.Column('max_violations', sa.Integer(), nullable=False),
    sa.Column('time_penalty_minutes', sa.Integer(), nullable=False),
    sa.Column('block_keyboard_shortcuts', sa.Boolean(), nullable=False),
    sa.Column('tab_switch_detection', sa.Boolean(), nullable=False),
    sa.Column('devtools_detection', sa.Boolean(), nullable=False),
    sa.Column('right_click_block', sa.Boolean(), nullable=False),
    sa.Column('copy_paste_block', sa.Boolean(), nullable=False),
    sa.Column('webcam_proctoring', sa.Boolean(), nullable=False),
    sa.Column('access_token', sa.UUID(), nullable=False),
    sa.Column('password_protected', sa.Boolean(), nullable=False),
    sa.Column('access_password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_assessments_group_id_groups')),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_assessments_teacher_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessments')),
    sa.UniqueConstraint('access_token', name=op.f('uq_assessments_access_token'))
    )
    op.create_table('group_enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_group_enrollments_group_id_groups')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_group_enrollments_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_enrollments')),
    sa.UniqueConstraint('group_id', 'student_id', name='uq_group_student')
    )
    op.create_table('performance_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('period_label', sa.String(length=50), nullable=False),
    sa.Column('assessments_taken', sa.Integer(), nullable=False),
    sa.Column('assessments_passed', sa.Integer(), nullable=False),
    sa.Column('avg_score', sa.Float(), nullable=True),
    sa.Column('best_score', sa.Float(), nullable=True),
    sa.Column('worst_score', sa.Float(), nullable=True),
    sa.Column('improvement_rate', sa.Float(), nullable=True),
    sa.Column('violation_total', sa.Integer(), nullable=False),
    sa.Column('at_risk', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_performance_snapshots_group_id_groups')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_performance_snapshots_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_performance_snapshots'))
    )
    op.create_table('assessment_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('time_remaining_seconds', sa.Integer(), nullable=True),
    sa.Column('score_raw', sa.Float(), nullable=True),
    sa.Column('score_percent', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('violation_count', sa.Integer(), nullable=False),
    sa.Column('termination_reason', sa.String(length=255), nullable=True),
    sa.Column('server_token', sa.UUID(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_assessment_attempts_assessment_id_assessments')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_assessment_attempts_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_attempts'))
    )
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=True),
    sa.Column('question_bank_id', sa.UUID(), nullable=True),
    sa.Column('question_type', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('partial_scoring', sa.Boolean(), nullable=False),
    sa.Column('negative_marking', sa.Float(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('topic_tag', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('blooms_level', sa.String(length=30), nullable=True),
    sa.Column('time_suggestion_seconds', sa.Integer(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_questions_assessment_id_assessments')),
    sa.ForeignKeyConstraint(['question_bank_id'], ['question_banks.id'], name=op.f('fk_questions_question_bank_id_question_banks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    op.create_table('question_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('match_key', sa.String(length=255), nullable=True),
    sa.Column('category_key', sa.String(length=255), nullable=True),
    sa.Column('order_position', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_question_options_question_id_questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_options'))
    )
    op.create_table('student_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('selected_option_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('matched_pairs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ordered_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('categorized', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hotspot_coords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('code_submission', sa.Text(), nullable=True),
    sa.Column('numeric_answer', sa.Float(), nullable=True),
    sa.Column('likert_value', sa.Integer(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('score_awarded', sa.Float(), nullable=True),
    sa.Column('auto_graded', sa.Boolean(), nullable=True),
    sa.Column('teacher_feedback', sa.Text(), nullable=True),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['assessment_attempts.id'], name=op.f('fk_student_answers_attempt_id_assessment_attempts')),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_student_answers_question_id_questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_answers'))
    )
    op.create_table('violations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('violation_type', sa.String(length=50), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_remaining_at_event', sa.Integer(), nullable=True),
    sa.Column('time_deducted_seconds', sa.Integer(), nullable=False),
    sa.Column('violation_count_after', sa.Integer(), nullable=False),
    sa.Column('browser_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_violations_assessment_id_assessments')),
    sa.ForeignKeyConstraint(['attempt_id'], ['assessment_attempts.id'], name=op.f('fk_violations_attempt_id_assessment_attempts')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_violations_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_violations'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('violations')
    op.drop_table('student_answers')
    op.drop_table('question_options')
    op.drop_table('questions')
    op.drop_table('assessment_attempts')
    op.drop_table('performance_snapshots')
    op.drop_table('group_enrollments')
    op.drop_table('assessments')
    op.drop_table('question_banks')
    op.drop_table('notifications')
    op.drop_table('groups')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('departments')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
